name: riak-aws
director_uuid: 42e99fc6-2c3b-4c20-8e72-f843efb25c13

releases:
- name: riak
  version: latest

compilation:
  workers: 2
  network: riak-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random
    instance_type: m1.small
    availability_zone: us-east-1d
    subnet: subnet-6c892647
update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: common
  network: riak-network
  size: 4
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    name: random
    instance_type: m1.small
    availability_zone: us-east-1d
    subnet: subnet-6c892647

networks:
- name: riak-network
  subnets:
<% (0..28).each_with_index do |i| %>
  - range: 10.0.1.<%= i*4 %>/30
    reserved:
      - 10.0.1.<%= i*4 + 1 %>
    static:
      - 10.0.1.<%= i*4 + 2 %>
    cloud_properties:
      name: random
      subnet: subnet-6c892647
<% end %>
<% (29..61).each_with_index do |i| %>
  - range: 10.0.1.<%= i*4 %>/30
    reserved:
      - 10.0.1.<%= i*4 + 1 %>
    cloud_properties:
      name: random
      instance_type: m1.small
      availability_zone: us-east-1d
      subnet: subnet-6c892647
<% end %>
<% (62..63).each_with_index do |i| %>
  - range: 10.0.1.<%= i*4 %>/30
    reserved:
      - 10.0.1.<%= i*4 + 1 %>
    static:
      - 10.0.1.<%= i*4 + 2 %>
    cloud_properties:
      name: random
      subnet: subnet-6c892647
<% end %>

jobs: 
- name: riak
  template: riak
  instances: 4
  resource_pool: common
  networks:
  - name: riak-network
    static_ips:
    - 10.0.1.2
    - 10.0.1.6
    - 10.0.1.10
    - 10.0.1.14
  persistent_disk: 4096

properties:
  riak:
    seed_node: 10.0.1.2
